[package]
name = "kanoko"
version = "0.1.0"
edition = "2024"

[dependencies]
color = "0.3.2"
itertools = "0.14.0"
rand = "0.9.2"
rand_distr = "0.5.1"
svg = "0.18.0"

[dev-dependencies]
clap = { version = "4.5.53", features = ["derive"] }
